### ISSUE TITLE
Webcam

### ISSUE THREAD

**Issue by PatrikPatrik2** [AndreaFavero71/CUBOTino_base_version#5]
Thanks for a fantastic project!!!!!

However, I have one issue with the webcam - it basically allways makes some error, but most often I can not get the data that the webcam read into the gui for manual correction, instead the webcam session restarts from the beginig, or I can return to the GUI, but there is no data from the web cam in the gui.

It would be really helpfull to have the "wrong" data in the gui, so I can manually correct

**Comment by AndreaFavero71** [comment]
I consciously decided to don't return incoherent cube status, from the Webcam reading to the GUI.
I believe the time needed to correct the cube status on the GUI takes more time than repeating the process via the Webcam.

In order to improve the cube status detection via the Webcam, please consider:
1) The light should possibly be diffused, or coming perpendicular to the webcam.
2) The cube facelets shouldn't preferably be too shining; With sand paper (Grit 1000 or 2000) it is possible to make the surface matt, also on cubes having labels.
3) In case of light reflection, due to the PC screen light source, it is convenient to keep the cube front face inclined (not parallel to the screen/webcam).
4) In case of logos, it is preferred to scratch them out.

If these tips won't help your case, I might consider to add a parameter to let users deciding to return incoherent cube status to the GUI....

**Comment by PatrikPatrik2** [comment]
Thanks for your quick response, I manage to get the video working, although it required a bit of cleaning of the cube!

Thanks again for an excellent project - it was a great Christmas project for me and my kids!

**Comment by AndreaFavero71** [comment]
When the cube facelets are polluted or damaged (i.e. holes on the stickers), it will be convenient to set "estimate facelets" in the  Settings window page.
When selected, the webcam is "stopped" once 7 facelets with proper characteristics are found; the position of the latest two facelets is estimated based on the position of the 7 detected ones.
Perhaps this setting makes the reading of your cube easier.

Note: This setting is released each time the GUI is closed, therefore it has to be selected each time the program is loaded.
